/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FreezeRouteImport } from './routes/freeze'
import { Route as MobileRouteImport } from './routes/mobile'
import { Route as AvroRouteImport } from './routes/avro'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as PaySlugRouteImport } from './routes/pay/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FreezeRoute = FreezeRouteImport.update({
  id: '/freeze',
  path: '/freeze',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const AvroRoute = AvroRouteImport.update({
  id: '/avro',
  path: '/avro',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const PaySlugRoute = PaySlugRouteImport.update({
  id: '/pay/$slug',
  path: '/pay/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/freeze': typeof FreezeRoute
  '/mobile': typeof MobileRoute
  '/avro': typeof AvroRoute
  '/pay/$slug': typeof PaySlugRoute
  '/docs': typeof DocsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/freeze': typeof FreezeRoute
  '/mobile': typeof MobileRoute
  '/avro': typeof AvroRoute
  '/pay/$slug': typeof PaySlugRoute
  '/docs': typeof DocsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/freeze': typeof FreezeRoute
  '/mobile': typeof MobileRoute
  '/avro': typeof AvroRoute
  '/pay/$slug': typeof PaySlugRoute
  '/docs': typeof DocsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/freeze' | '/mobile' | '/avro' | '/docs' | '/pay/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/freeze' | '/mobile' | '/avro' | '/docs' | '/pay/$slug'
  id: '__root__' | '/' | '/freeze' | '/mobile' | '/avro' | '/docs' | '/pay/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FreezeRoute: typeof FreezeRoute
  MobileRoute: typeof MobileRoute
  AvroRoute: typeof AvroRoute
  DocsRoute: typeof DocsRoute
  PaySlugRoute: typeof PaySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freeze': {
      id: '/freeze'
      path: '/freeze'
      fullPath: '/freeze'
      preLoaderRoute: typeof FreezeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avro': {
      id: '/avro'
      path: '/avro'
      fullPath: '/avro'
      preLoaderRoute: typeof AvroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$slug': {
      id: '/pay/$slug'
      path: '/pay/$slug'
      fullPath: '/pay/$slug'
      preLoaderRoute: typeof PaySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FreezeRoute: FreezeRoute,
  MobileRoute: MobileRoute,
  AvroRoute: AvroRoute,
  DocsRoute: DocsRoute,
  PaySlugRoute: PaySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
